name: CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    rust:
        name: Rust
        uses: RustForWeb/.github/.github/workflows/rust.yml@d6e6ead9b4da3d70245d3ee4e06fe339244bb200
