name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: RustForWeb/.github/.github/workflows/release.yml@d6e6ead9b4da3d70245d3ee4e06fe339244bb200
        with:
            bump: ${{ inputs.bump }}
