name: Website

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
    contents: read
    id-token: write
    pages: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    book:
        name: Book
        uses: RustForWeb/.github/.github/workflows/book.yml@d6e6ead9b4da3d70245d3ee4e06fe339244bb200
        with:
            combine: false
            clean-options: '-p fortifier -p regex'
            build-options: '-p fortifier --features all-validations -p regex'
